# Generated by Django 2.0.3 on 2018-04-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(height_field='height', max_length=255, upload_to='images/', width_field='width')),
            ],
        ),
    ]
