# Generated by Django 2.0.3 on 2018-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_horror_romance_thriller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comedy',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='horror',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='romance',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='thriller',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
