# Generated by Django 2.0.3 on 2018-04-18 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='img/1.jpg', upload_to='img'),
        ),
    ]
