# Generated by Django 2.0.3 on 2018-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_movie_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='./media/img/1.jpg', upload_to='./media/img'),
        ),
    ]
