# Generated by Django 2.0.3 on 2018-04-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180418_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='comedy',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='horror',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='romance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='thriller',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
