# Generated by Django 2.0.3 on 2018-04-19 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20180418_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='movie_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.Movie'),
        ),
    ]
