# Generated by Django 2.0.3 on 2018-04-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_comment_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='text',
            field=models.TextField(default='dfd'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
    ]
