# Generated by Django 2.0.3 on 2018-04-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_register'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorites',
            name='image',
        ),
    ]
