# Generated by Django 2.0.3 on 2018-04-20 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_favorites_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
